
name: Publish to TestPyPI

# on:
#   release:
#     types:
#       - released
on:
  workflow_dispatch:
    inputs:
      releasetag:
        description: 'Release Tag'
        required: true
        type: string
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  publish:
    name: Publish to TestPyPI
    runs-on: ubuntu-24.04

    environment:
      name: testpypi
      url: https://test.pypi.org/p/jitxlib-deploytest1

    permissions:
      contents: read   # for reading content from a repo
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:

      - name: Debug Dump GitHub context
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Debug list artifact files
        shell: bash
        run: |
            ls -la || true

      - name: Fetch Release
        uses: robinraju/release-downloader@v1
        with:
          repository: ${{ github.repository }}
          #tag: ${{ github.ref_name }}
          tag: ${{ inputs.releasetag }}
          fileName: '*'
          out-file-path: dist/
          extract: false

      - name: Debug list artifact files
        shell: bash
        run: |
            ls -la dist/ || true

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist/

